<?xml version="1.0" encoding="ISO-8859-1"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>hu.blackbelt.bundles.odfdom</groupId>
    <artifactId>org.odftoolkit.odfdom-java</artifactId>
    <packaging>bundle</packaging>
    <version>0.12.0_1</version>
    <name>odfdom</name>
    <description>odfdom</description>

    <properties>
        <odfdom.version>0.12.0</odfdom.version>
    </properties>

    <url>http://github.com/BlackBeltTechnology/osgi-repackaged-bundles</url>
    <issueManagement>
        <url>https://github.com/BlackBeltTechnology/osgi-repackaged-bundles</url>
        <system>GitHub Issues</system>
    </issueManagement>

    <scm>
        <connection>scm:git:git://github.com/BlackBeltTechnology/osgi-repackaged-bundles.git</connection>
        <developerConnection>scm:git:ssh://${git.username}@github.com:BlackBeltTechnology/osgi-repackaged-bundles.git</developerConnection>
        <url>http://github.com/BlackBeltTechnology/osgi-repackaged-bundles</url>
        <tag>HEAD</tag>
    </scm>

    <developers>
        <developer>
            <id>robson</id>
            <name>Robert Csakany</name>
            <email>robert.csakany@blackbelt.hu</email>
            <url>https://github.com/robertcsakany</url>
            <organization>BlackBelt Technology</organization>
            <organizationUrl>http://www.blackbelt.hu</organizationUrl>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <profiles>
        <profile>
            <id>sign-artifacts</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.simplify4u.plugins</groupId>
                        <artifactId>sign-maven-plugin</artifactId>
                        <version>1.0.1</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>release-judong</id>
            <distributionManagement>
                <snapshotRepository>
                    <id>judong-nexus-distribution</id>
                    <!--suppress UnresolvedMavenProperty -->
                    <url>https://nexus.judo.technology/repository/maven-judong-snapshots/</url>
                </snapshotRepository>
                <repository>
                    <id>judong-nexus-distribution</id>
                    <!--suppress UnresolvedMavenProperty -->
                    <url>https://nexus.judo.technology/repository/maven-judong-snapshots/</url>
                </repository>
            </distributionManagement>
        </profile>

        <profile>
            <id>release-central</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.sonatype.plugins</groupId>
                        <artifactId>nexus-staging-maven-plugin</artifactId>
                        <version>1.7.0</version>
                        <extensions>true</extensions>
                        <configuration>
                            <serverId>ossrh</serverId>
                            <nexusUrl>https://ossrh-staging-api.central.sonatype.com/</nexusUrl>
                            <autoReleaseAfterClose>true</autoReleaseAfterClose>
                            <stagingProgressTimeoutMinutes>15</stagingProgressTimeoutMinutes>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
            <distributionManagement>
                <snapshotRepository>
                    <id>ossrh</id>
                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                </snapshotRepository>
                <repository>
                    <id>ossrh</id>
                    <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
                </repository>
            </distributionManagement>
        </profile>
    </profiles>

    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>2.8.2</version>
            </plugin>

            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <version>5.1.8</version>
                <extensions>true</extensions>
                <configuration>
                    <instructions>
                        <_exportcontents>
                            org.odftoolkit.odfdom.*;version="${odfdom.version}"
                        </_exportcontents>
                        <!-- bundle supplied resource prefixes -->
                        <Include-Resource>{maven-resources}</Include-Resource>

                        <!-- Do not inline jars, include as jar files -->
                        <!-- There are config files with same name will be overwritten -->
                        <Embed-Dependency>*;scope=compile;inline=false</Embed-Dependency>
                        <Import-Package>
                            java.awt,
                            java.awt.image,
                            java.io,java.lang,
                            java.lang.invoke,
                            java.lang.reflect,
                            java.net,
                            java.nio.charset,
                            java.nio.file,
                            java.security,
                            java.security.spec,
                            java.text,
                            java.util,
                            java.util.jar,
                            java.util.logging,
                            java.util.regex,
                            java.util.zip,
                            javax.crypto,
                            javax.crypto.spec,
                            javax.imageio,
                            javax.xml.datatype,
                            javax.xml.namespace,
                            javax.xml.parsers,
                            javax.xml.stream,
                            javax.xml.stream.events,
                            javax.xml.transform,
                            javax.xml.transform.dom,
                            javax.xml.transform.sax,
                            javax.xml.transform.stream,
                            javax.xml.xpath,net.rootdev.javardfa;version="[1.0,2)",
                            net.rootdev.javardfa.literal;version="[1.0,2)",
                            net.rootdev.javardfa.uri;version="[1.0,2)",
                            org.apache.commons.compress.archivers.zip;version="[1.25,2)",
                            org.apache.commons.lang3.time;version="[3.14,4)",
                            org.apache.commons.validator.routines;version="[1.7,2)",
                            org.apache.jena.rdf.model,
                            org.apache.jena.util,
                            org.apache.xerces.dom,
                            org.apache.xerces.impl.dv,
                            org.apache.xerces.impl.dv.util,
                            org.apache.xerces.impl.validation,
                            org.apache.xerces.jaxp,
                            org.apache.xerces.jaxp.datatype,
                            org.apache.xml.serializer,
                            org.json;version="[20231013.0,20231014)",
                            *
                        </Import-Package>

                    </instructions>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <dependencies>

        <!-- Embedded dependencies -->
        <dependency>
            <groupId>org.odftoolkit</groupId>
            <artifactId>odfdom-java</artifactId>
            <version>0.12.0</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.apache.jena/jena-core -->
        <dependency>
            <groupId>org.apache.jena</groupId>
            <artifactId>jena-core</artifactId>
            <version>4.1.0</version>
        </dependency>
    </dependencies>

</project>
